language: node_js
node_js:
  - "8"
services:
  - mongodb
after_script: NODE_ENV=test ./node_modules/.bin/mocha --timeout 5000 --exit && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
